CREATE TABLE TEACHERS(
id INT IDENTITY PRIMARY KEY,
NAME VARCHAR(50),
SUBJECT VARCHAR(50)
)

CREATE TABLE STUDENTS(
id INT IDENTITY PRIMARY KEY,
NAME VARCHAR(50),
AGE INT,
COURSE VARCHAR(50),
GRADE VARCHAR(50),
CLASS_TEACHER INT NOT NULL
)

CREATE TABLE MARKS(
id INT IDENTITY PRIMARY KEY,
STUDENT_ID INT NOT NULL,
TAMIL INT,
ENGLISH INT,
MATHS INT,
SCIENCE INT,
SOCIAL_SCIENCE INT
)

ALTER TABLE STUDENTS
ADD CONSTRAINT FK_ClassTeacher
FOREIGN KEY (CLASS_TEACHER) REFERENCES TEACHERS(id)

ALTER TABLE MARKS
ADD CONSTRAINT FK_StudentId
FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(id)

CREATE TABLE Users(
id INT IDENTITY PRIMARY KEY,
username VARCHAR(500),
password VARCHAR(500)
)

TRUNCATE TABLE Users
